version: "3.9"
services:
  chanchito: #nombre contenedor
    build: . #ruta de la imagen (dockerfile)
    ports: 
      - "3000:3000" #puerto_anfitrion:puerto_contenedor
    links:
      - monguito #nombre del contenedor a mapear
  monguito: #nombre contenedor
    image: mongo #nombre de la imagen
    ports:
      - "27017:27017" #puerto_anfitrion:puerto_contenedor
    environment: #variables de entorno
      - MONGO_INITDB_ROOT_USERNAME=rmedina
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db #indica el volumen que va a usar:ruta donde guarda los datos
      
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes: #definir volumenes
  mongo-data: #nombre del volumen
